// Can not be configured by Conventions-Plugin.
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}

// Without rootProject.name the Name of the Projekt-Directory is used.
// rootProject.name = "base"

// include("blobstore-api")
// include("arser-configuration")
include("arser-core")
include("arser-server-jre")
// include("arser-server-spring")
// include("arser-application")
