group = de.freese.arser.test
version = 0.0.1-SNAPSHOT

description = Arser Test

org.gradle.jvmargs = -Xmx4096m -XX:MaxMetaspaceSize=2048m -Dfile.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
file.encoding = UTF-8

systemProp.gradle.user.home = /tmp/.gradle-arser

version_slf4j = 2.0.18
version_gradleToolingApi = 9.7.1
version_junit = 6.1.3
